// Country-specific metadata for international TMS clinic pages

export interface CountryMeta {
    code: string;
    name: string;
    urlPrefix: string;
    flag: string;
    currency: string;
    publicHealthSystem: string;
    tmsStatus: string;
    sessionCostRange: string;
    seoDescription: string;
    aboutContent: string;
    insuranceNote: string;
}

export const COUNTRY_META: Record<string, CountryMeta> = {
    GB: {
        code: 'GB',
        name: 'United Kingdom',
        urlPrefix: 'uk',
        flag: '\u{1F1EC}\u{1F1E7}',
        currency: 'GBP',
        publicHealthSystem: 'NHS',
        tmsStatus: 'NICE-approved since 2015',
        sessionCostRange: '\u00A3200\u2013\u00A3400',
        seoDescription: 'TMS therapy is NICE-approved in the UK for treatment-resistant depression. While NHS access remains limited, private clinics across England, Scotland, and Wales offer advanced rTMS and Deep TMS protocols.',
        aboutContent: 'The UK has a growing network of TMS providers, led by Smart TMS with clinics nationwide and specialist Harley Street practices in London. The Maudsley Hospital is one of the few NHS providers. NICE approved TMS for depression in 2015, but NHS commissioning varies by region.',
        insuranceNote: 'TMS is NICE-approved but NHS access is extremely limited. Most patients pay privately. Some private health insurers (Bupa, AXA PPP, Aviva) may cover TMS with pre-authorisation.',
    },
    CA: {
        code: 'CA',
        name: 'Canada',
        urlPrefix: 'ca',
        flag: '\u{1F1E8}\u{1F1E6}',
        currency: 'CAD',
        publicHealthSystem: 'Provincial Health Plans (OHIP, MSP, RAMQ)',
        tmsStatus: 'Health Canada approved',
        sessionCostRange: 'CA$200\u2013CA$500',
        seoDescription: 'TMS therapy is Health Canada approved for treatment-resistant depression. Clinics across Ontario, British Columbia, Alberta, and Quebec offer both standard rTMS and BrainsWay Deep TMS protocols.',
        aboutContent: 'Canada has TMS clinics in major cities from coast to coast. While provincial health plans (OHIP, MSP, RAMQ) generally do not cover TMS, some extended employer health benefits may provide partial coverage. Academic centres like MUHC Montreal also offer clinical TMS programs.',
        insuranceNote: 'Provincial health plans do not cover TMS. Some extended employer health insurance plans may partially cover treatment. Most patients pay out of pocket, with some clinics offering payment plans.',
    },
    AU: {
        code: 'AU',
        name: 'Australia',
        urlPrefix: 'au',
        flag: '\u{1F1E6}\u{1F1FA}',
        currency: 'AUD',
        publicHealthSystem: 'Medicare Australia',
        tmsStatus: 'TGA-approved, Medicare-rebated since 2021',
        sessionCostRange: 'A$100\u2013A$300 (after Medicare rebate)',
        seoDescription: 'Australia leads internationally in TMS accessibility \u2014 Medicare rebates have been available since November 2021 for treatment-resistant depression. Clinics across NSW, Victoria, and Queensland offer rTMS and Deep TMS.',
        aboutContent: 'Australia is one of the most accessible countries for TMS therapy, with Medicare rebates available since November 2021 for treatment-resistant depression. This makes TMS significantly more affordable than in most other countries. Major providers include Sydney TMS, NeuroCentrix, neurocare clinics, and Monarch Mental Health Group.',
        insuranceNote: 'Medicare Australia provides rebates for TMS treatment of treatment-resistant depression (MBS item numbers apply). A GP referral and psychiatrist oversight are required. Private health insurance may cover the gap. Out-of-pocket costs are typically A$100\u2013A$300 per session after rebate.',
    },
    DE: {
        code: 'DE',
        name: 'Germany',
        urlPrefix: 'de',
        flag: '\u{1F1E9}\u{1F1EA}',
        currency: 'EUR',
        publicHealthSystem: 'Gesetzliche Krankenversicherung (GKV)',
        tmsStatus: 'CE-marked, available in university hospitals',
        sessionCostRange: '\u20AC150\u2013\u20AC350',
        seoDescription: 'TMS therapy is available at leading university hospitals and private practices across Germany. Statutory health insurance (GKV) may cover treatment in clinical settings for treatment-resistant depression.',
        aboutContent: 'Germany has TMS available primarily through university hospitals (like Charit\u00E9 Berlin) and specialised private practices. The neurocare group, headquartered in Munich, is a major TMS device manufacturer and clinical provider. Statutory health insurance coverage for TMS varies by provider and clinical setting.',
        insuranceNote: 'Statutory health insurance (GKV) may cover rTMS for depression in university hospital settings. Private health insurance (PKV) coverage varies by plan. Many private practices require self-pay.',
    },
    IN: {
        code: 'IN',
        name: 'India',
        urlPrefix: 'in',
        flag: '\u{1F1EE}\u{1F1F3}',
        currency: 'INR',
        publicHealthSystem: 'Government Hospitals',
        tmsStatus: 'Available at government and private institutions',
        sessionCostRange: '\u20B93,000\u2013\u20B95,000 (approx. US$35\u201360)',
        seoDescription: 'TMS therapy is available at premier institutions like NIMHANS Bangalore and growing private clinic networks across Delhi, Bangalore, and other major cities. India offers some of the most affordable TMS treatment globally.',
        aboutContent: 'India has a growing TMS therapy landscape, led by NIMHANS (National Institute of Mental Health and Neuro Sciences) in Bangalore \u2014 one of Asia\'s foremost mental health institutions. Private clinics like Mindful TMS Neurocare operate across multiple cities. TMS treatment in India is significantly more affordable than in Western countries.',
        insuranceNote: 'Government hospitals like NIMHANS offer subsidised rates. Private clinic sessions cost approximately \u20B93,000\u2013\u20B95,000 (US$35\u201360). Most private health insurance plans in India do not yet cover TMS therapy.',
    },
    FR: {
        code: 'FR',
        name: 'France',
        urlPrefix: 'fr',
        flag: '\u{1F1EB}\u{1F1F7}',
        currency: 'EUR',
        publicHealthSystem: 'S\u00E9curit\u00E9 Sociale / Assurance Maladie',
        tmsStatus: 'CE-marked, available at university hospitals since 2014',
        sessionCostRange: '\u20AC150\u2013\u20AC350',
        seoDescription: 'TMS therapy is available at leading university hospitals (CHU) and private clinics across France. Paris, Lyon, Marseille, and Bordeaux offer advanced rTMS and Deep TMS protocols for treatment-resistant depression.',
        aboutContent: 'France has a well-established TMS therapy network, centred around university hospitals (CHU) in major cities. Pitié-Salpêtrière in Paris is a leading research centre for brain stimulation. Private clinics in Paris and the Riviera also offer TMS. French psychiatry has embraced neuromodulation, with the Société Française de Stimulation Transcrânienne supporting research and clinical practice.',
        insuranceNote: 'Sécurité Sociale may partially reimburse TMS when performed at a public hospital under specific clinical protocols. Private clinics typically require out-of-pocket payment or complementary insurance (mutuelle). Costs range from \u20AC150\u2013\u20AC350 per session.',
    },
    JP: {
        code: 'JP',
        name: 'Japan',
        urlPrefix: 'jp',
        flag: '\u{1F1EF}\u{1F1F5}',
        currency: 'JPY',
        publicHealthSystem: 'National Health Insurance (NHI)',
        tmsStatus: 'Approved by MHLW for treatment-resistant depression since 2019',
        sessionCostRange: '\u00A510,000\u2013\u00A530,000 (approx. US$70\u2013200)',
        seoDescription: 'TMS therapy was approved in Japan in 2019 by the Ministry of Health. Leading university hospitals in Tokyo, Osaka, and Kyoto offer NHI-covered TMS for treatment-resistant depression.',
        aboutContent: 'Japan approved rTMS for treatment-resistant depression in June 2019, making it one of the first Asian countries to provide national health insurance coverage. Keio University Hospital and the National Center of Neurology and Psychiatry in Tokyo are leading providers. The NeuroStar system is the primary device used under NHI coverage.',
        insuranceNote: 'National Health Insurance (NHI) covers TMS for treatment-resistant depression at approved medical institutions. Patients pay the standard 30% co-pay. Not all hospitals are approved for NHI-covered TMS — check with the facility. Private clinics offering TMS outside NHI charge \u00A510,000\u2013\u00A530,000 per session.',
    },
    KR: {
        code: 'KR',
        name: 'South Korea',
        urlPrefix: 'kr',
        flag: '\u{1F1F0}\u{1F1F7}',
        currency: 'KRW',
        publicHealthSystem: 'National Health Insurance Service (NHIS)',
        tmsStatus: 'MFDS-approved, available at university hospitals',
        sessionCostRange: '\u20A9100,000\u2013\u20A9250,000 (approx. US$75\u2013190)',
        seoDescription: 'TMS therapy is available at leading university hospitals and private psychiatric clinics across South Korea. Seoul, Busan, and Daegu offer advanced rTMS protocols for depression and other conditions.',
        aboutContent: 'South Korea has a growing TMS therapy landscape, driven by research at Seoul National University Hospital, Samsung Medical Center, and Asan Medical Center. Korean psychiatrists have published extensively on TMS for depression and cognitive enhancement. Private neuropsychiatric clinics in Gangnam and other affluent districts also offer TMS.',
        insuranceNote: 'NHIS coverage for TMS is limited and varies by hospital and indication. Most patients at private clinics pay out of pocket. University hospital rates may be partially covered under specific research protocols. Sessions cost approximately \u20A9100,000\u2013\u20A9250,000.',
    },
    BR: {
        code: 'BR',
        name: 'Brazil',
        urlPrefix: 'br',
        flag: '\u{1F1E7}\u{1F1F7}',
        currency: 'BRL',
        publicHealthSystem: 'SUS (Sistema Único de Saúde)',
        tmsStatus: 'ANVISA-approved, CFM-regulated since 2012',
        sessionCostRange: 'R$300\u2013R$800 (approx. US$55\u2013150)',
        seoDescription: 'Brazil is a global leader in TMS research with ANVISA-approved treatment available at university hospitals and private clinics in São Paulo, Rio de Janeiro, and other major cities.',
        aboutContent: 'Brazil is internationally recognised for TMS research, with the University of São Paulo (USP) and Instituto de Psiquiatria leading global clinical trials. The Brazilian Federal Council of Medicine (CFM) approved rTMS as a therapeutic procedure in 2012. São Paulo has the highest concentration of TMS providers in Latin America. Brazilian researchers have contributed significantly to theta burst stimulation protocols.',
        insuranceNote: 'SUS (public health) does not routinely cover TMS, though some university hospitals offer it through research programs. Private health insurance (planos de saúde) coverage varies by plan — ANS (national agency) has been evaluating inclusion. Most patients pay privately, with sessions costing R$300\u2013R$800.',
    },
    ES: {
        code: 'ES',
        name: 'Spain',
        urlPrefix: 'es',
        flag: '\u{1F1EA}\u{1F1F8}',
        currency: 'EUR',
        publicHealthSystem: 'Sistema Nacional de Salud (SNS)',
        tmsStatus: 'CE-marked, available at public and private hospitals',
        sessionCostRange: '\u20AC100\u2013\u20AC300',
        seoDescription: 'TMS therapy is available at university hospitals and private clinics across Spain. Madrid, Barcelona, Valencia, and Seville offer rTMS and Deep TMS for treatment-resistant depression.',
        aboutContent: 'Spain has TMS available at major university hospitals including Hospital Clínic de Barcelona, Hospital Universitario 12 de Octubre in Madrid, and Hospital La Fe in Valencia. Private clinics in Madrid and Barcelona offer advanced protocols. Spanish TMS research has focused on treatment-resistant depression and fibromyalgia applications.',
        insuranceNote: 'Public health system (SNS) access to TMS is limited to specific hospital programs and clinical trials. Private health insurance (Sanitas, Adeslas, MAPFRE) may cover TMS with pre-authorisation. Most private clinic patients pay \u20AC100\u2013\u20AC300 per session.',
    },
    IT: {
        code: 'IT',
        name: 'Italy',
        urlPrefix: 'it',
        flag: '\u{1F1EE}\u{1F1F9}',
        currency: 'EUR',
        publicHealthSystem: 'Servizio Sanitario Nazionale (SSN)',
        tmsStatus: 'CE-marked, available at university hospitals and private clinics',
        sessionCostRange: '\u20AC120\u2013\u20AC300',
        seoDescription: 'TMS therapy is offered at leading Italian university hospitals and private clinics. Milan, Rome, Bologna, and Padua are key centres for rTMS treatment of depression and neurological conditions.',
        aboutContent: 'Italy has a strong tradition of TMS research, with contributions from institutions like Università Vita-Salute San Raffaele in Milan and Fondazione Santa Lucia in Rome. Italian neuroscientists have been at the forefront of TMS research methodology. Clinical TMS is available at university hospitals in most major cities, with a growing number of private clinics offering treatment.',
        insuranceNote: 'SSN (public health) may cover TMS at university hospitals under specific clinical pathways. Private treatment costs \u20AC120\u2013\u20AC300 per session. Some private insurance plans cover partial costs with a referral from a psychiatrist.',
    },
    NL: {
        code: 'NL',
        name: 'Netherlands',
        urlPrefix: 'nl',
        flag: '\u{1F1F3}\u{1F1F1}',
        currency: 'EUR',
        publicHealthSystem: 'Zorgverzekeringswet (Zvw)',
        tmsStatus: 'CE-marked, included in basic insurance package for specific indications',
        sessionCostRange: '\u20AC150\u2013\u20AC350',
        seoDescription: 'TMS therapy is well-established in the Netherlands, with health insurance coverage available for treatment-resistant depression. Amsterdam, Utrecht, and Rotterdam have leading TMS centres.',
        aboutContent: 'The Netherlands is one of the most accessible European countries for TMS therapy. Dutch health insurers increasingly cover rTMS for treatment-resistant depression as part of specialised mental healthcare (SGGZ). Academic medical centres like Amsterdam UMC and UMC Utrecht are leading research institutions. The brainclinics research institute in Nijmegen is a major contributor to personalised TMS protocols.',
        insuranceNote: 'Basic health insurance (basisverzekering) may cover TMS as part of specialised mental healthcare (SGGZ) when referred by a psychiatrist. A referral pathway through the GP and psychiatrist is required. Patients pay the standard deductible (eigen risico). Private clinics charge \u20AC150\u2013\u20AC350 per session for self-pay patients.',
    },
    SG: {
        code: 'SG',
        name: 'Singapore',
        urlPrefix: 'sg',
        flag: '\u{1F1F8}\u{1F1EC}',
        currency: 'SGD',
        publicHealthSystem: 'MediShield Life / Public Hospitals',
        tmsStatus: 'HSA-registered, available at public and private hospitals',
        sessionCostRange: 'S$200\u2013S$500 (approx. US$150\u2013370)',
        seoDescription: 'TMS therapy is available at Singapore\'s leading hospitals including NUH, IMH, and private psychiatric clinics. Singapore is a regional hub for advanced neuromodulation in Southeast Asia.',
        aboutContent: 'Singapore offers TMS at both public institutions and private clinics. The Institute of Mental Health (IMH) and National University Hospital (NUH) provide TMS within comprehensive psychiatric care programs. Private providers in Orchard Road and Novena medical hubs offer premium TMS services. Singapore serves as a medical tourism destination for TMS patients across Southeast Asia.',
        insuranceNote: 'MediShield Life and MediSave generally do not cover TMS. Some private insurers (Great Eastern, Prudential, AIA) may provide partial coverage with pre-approval. Most patients pay out of pocket. Public hospital rates are subsidised for Singapore citizens and PRs. Sessions cost S$200\u2013S$500.',
    },
    AE: {
        code: 'AE',
        name: 'United Arab Emirates',
        urlPrefix: 'ae',
        flag: '\u{1F1E6}\u{1F1EA}',
        currency: 'AED',
        publicHealthSystem: 'DHA (Dubai) / HAAD (Abu Dhabi)',
        tmsStatus: 'Available at private hospitals and specialist clinics',
        sessionCostRange: 'AED 800\u2013AED 2,000 (approx. US$220\u2013545)',
        seoDescription: 'TMS therapy is available at premium hospitals and psychiatric clinics in Dubai, Abu Dhabi, and Sharjah. The UAE is a growing hub for advanced mental health treatment in the Middle East.',
        aboutContent: 'The UAE has rapidly expanded its TMS offerings, particularly in Dubai and Abu Dhabi. Premium hospitals like American Hospital Dubai, Cleveland Clinic Abu Dhabi, and Priory Wellbeing Centre offer TMS with internationally trained psychiatrists. The UAE attracts medical tourists from across the GCC and wider Middle East for neuromodulation treatment.',
        insuranceNote: 'Mandatory health insurance in Dubai and Abu Dhabi may cover TMS with pre-authorisation, depending on the plan tier. Premium insurance plans from Daman, Oman Insurance, and AXA Gulf are more likely to provide coverage. Many patients pay out of pocket. Sessions cost AED 800\u2013AED 2,000.',
    },
    NZ: {
        code: 'NZ',
        name: 'New Zealand',
        urlPrefix: 'nz',
        flag: '\u{1F1F3}\u{1F1FF}',
        currency: 'NZD',
        publicHealthSystem: 'ACC / Public Health System',
        tmsStatus: 'Available at DHB hospitals and private clinics',
        sessionCostRange: 'NZ$150\u2013NZ$400 (approx. US$90\u2013240)',
        seoDescription: 'TMS therapy is available in New Zealand at DHB hospitals in Auckland and Wellington, plus private clinics. Treatment options are expanding for depression and other conditions.',
        aboutContent: 'New Zealand has a developing TMS landscape, with services available primarily in Auckland and Wellington. Auckland DHB and Capital & Coast DHB offer TMS within their psychiatry departments. Private clinics like TMS New Zealand provide treatment in major centres. Research at the University of Auckland supports growing clinical adoption.',
        insuranceNote: 'Public DHB-provided TMS may be available at no cost through referral for treatment-resistant depression, but wait times can be lengthy. Private clinic sessions cost NZ$150\u2013NZ$400. Southern Cross and other private insurers may cover TMS with specialist referral.',
    },
    ZA: {
        code: 'ZA',
        name: 'South Africa',
        urlPrefix: 'za',
        flag: '\u{1F1FF}\u{1F1E6}',
        currency: 'ZAR',
        publicHealthSystem: 'Public Health System / Medical Aid Schemes',
        tmsStatus: 'Available at private hospitals and psychiatric practices',
        sessionCostRange: 'R2,000\u2013R4,500 (approx. US$110\u2013250)',
        seoDescription: 'TMS therapy is available at private psychiatric clinics in Johannesburg, Cape Town, Pretoria, and Durban. South Africa leads TMS adoption in sub-Saharan Africa.',
        aboutContent: 'South Africa is the leading provider of TMS therapy in Africa, with clinics concentrated in Johannesburg, Cape Town, Pretoria, and Durban. Private psychiatric hospitals like Akeso and Netcare operate TMS programs. Academic institutions including the University of Cape Town and Wits University conduct TMS research. The South African Society of Psychiatrists recognises TMS as a treatment modality.',
        insuranceNote: 'Major medical aid schemes (Discovery Health, Momentum, Bonitas) may cover TMS with pre-authorisation and motivation from a psychiatrist. Coverage depends on the plan level. Out-of-pocket costs range from R2,000\u2013R4,500 per session. Public sector availability is extremely limited.',
    },
    SE: {
        code: 'SE',
        name: 'Sweden',
        urlPrefix: 'se',
        flag: '\u{1F1F8}\u{1F1EA}',
        currency: 'SEK',
        publicHealthSystem: 'Regionernas Hälso- och Sjukvård',
        tmsStatus: 'CE-marked, available at university hospitals',
        sessionCostRange: 'SEK 1,500\u2013SEK 3,500 (approx. US$140\u2013330)',
        seoDescription: 'TMS therapy is available at Swedish university hospitals and private clinics. Stockholm, Gothenburg, and Malmö offer evidence-based rTMS for treatment-resistant depression.',
        aboutContent: 'Sweden offers TMS therapy primarily through university hospitals in Stockholm (Karolinska), Gothenburg (Sahlgrenska), and Uppsala. Swedish healthcare regions have been gradually incorporating TMS into treatment pathways for depression. The Karolinska Institute is a leading European research centre for brain stimulation. Private clinics in Stockholm also offer TMS.',
        insuranceNote: 'Regional healthcare (landsting) may cover TMS at university hospitals under the högkostnadsskydd (high-cost protection) system, with patient fees capped at SEK 1,300 per year. Private clinic treatment costs SEK 1,500\u2013SEK 3,500 per session and is not covered by the public system.',
    },
    IE: {
        code: 'IE',
        name: 'Ireland',
        urlPrefix: 'ie',
        flag: '\u{1F1EE}\u{1F1EA}',
        currency: 'EUR',
        publicHealthSystem: 'HSE (Health Service Executive)',
        tmsStatus: 'CE-marked, available at private clinics',
        sessionCostRange: '\u20AC200\u2013\u20AC400',
        seoDescription: 'TMS therapy is available at private psychiatric clinics in Dublin, Cork, and Galway. Ireland has a growing network of TMS providers for treatment-resistant depression.',
        aboutContent: 'Ireland\'s TMS landscape is growing, with private clinics in Dublin leading the way. St Patrick\'s Mental Health Services and Hermitage Medical Clinic offer TMS programs. Trinity College Dublin conducts TMS research. While HSE (public health) access is limited, private provision is expanding to meet demand for treatment-resistant depression.',
        insuranceNote: 'HSE does not routinely fund TMS therapy. Private health insurers (VHI, Laya Healthcare, Irish Life Health) may cover TMS with psychiatrist referral and pre-approval, depending on the plan. Most patients pay \u20AC200\u2013\u20AC400 per session out of pocket.',
    },
    IL: {
        code: 'IL',
        name: 'Israel',
        urlPrefix: 'il',
        flag: '\u{1F1EE}\u{1F1F1}',
        currency: 'ILS',
        publicHealthSystem: 'Kupot Holim (Health Funds)',
        tmsStatus: 'MOH-approved, included in health basket since 2020',
        sessionCostRange: '\u20AA300\u2013\u20AA800 (approx. US$80\u2013220)',
        seoDescription: 'Israel is a global leader in TMS technology — BrainsWay Deep TMS was invented here. TMS is included in the national health basket, making it accessible through all four health funds.',
        aboutContent: 'Israel holds a unique position in TMS therapy as the birthplace of BrainsWay Deep TMS technology, invented at the Weizmann Institute of Science. TMS was added to the Israeli health basket in 2020, making it accessible through all four health funds (Kupot Holim). Beer Yaakov Mental Health Center and Shalvata Mental Health Center are major providers. Israeli researchers continue to pioneer new TMS protocols and applications.',
        insuranceNote: 'TMS is included in Israel\'s national health basket since 2020 and is covered by all four Kupot Holim (Clalit, Maccabi, Meuhedet, Leumit) for treatment-resistant depression. Patients pay standard co-pays. Private clinics charge \u20AA300\u2013\u20AA800 per session for faster access or additional indications.',
    },
    MX: {
        code: 'MX',
        name: 'Mexico',
        urlPrefix: 'mx',
        flag: '\u{1F1F2}\u{1F1FD}',
        currency: 'MXN',
        publicHealthSystem: 'IMSS / ISSSTE',
        tmsStatus: 'COFEPRIS-approved, available at private clinics and hospitals',
        sessionCostRange: 'MX$2,500\u2013MX$6,000 (approx. US$140\u2013340)',
        seoDescription: 'TMS therapy is available at private hospitals and psychiatric clinics in Mexico City, Guadalajara, Monterrey, and other major cities. Mexico offers affordable TMS treatment in Latin America.',
        aboutContent: 'Mexico has a growing TMS therapy market, centred in Mexico City, Guadalajara, and Monterrey. Private hospitals like Hospital Angeles, Médica Sur, and ABC Medical Center offer TMS programs. The National Institute of Psychiatry (INPRFM) in Mexico City conducts TMS research and clinical programs. Mexico is increasingly attracting medical tourists from the US seeking more affordable TMS treatment.',
        insuranceNote: 'IMSS and ISSSTE (public health) do not typically cover TMS. Private health insurance (GNP, AXA, Metlife México) may cover TMS with pre-authorisation. Many patients pay out of pocket. Sessions cost MX$2,500\u2013MX$6,000. Medical tourism packages are available at some clinics.',
    },
};

export function getCountryMeta(urlPrefix: string): CountryMeta | undefined {
    return Object.values(COUNTRY_META).find(c => c.urlPrefix === urlPrefix);
}

export function getCountryCodeFromPrefix(urlPrefix: string): string | undefined {
    const meta = getCountryMeta(urlPrefix);
    return meta?.code;
}
