/**
 * Blog Scheduler Manifest — May through December 2026
 * Each entry defines a blog post to auto-generate and publish.
 * Run `node scripts/generate-scheduled-blogs.mjs` to generate all posts.
 *
 * Categories: treatment | research | insurance | faq | patient-guide
 */

export const SCHEDULED_POSTS = [
  // ── MAY 2026 ──────────────────────────────────────────────────────────────
  {
    slug: 'neurostar-tms-device-review-2026',
    title: 'NeuroStar TMS Device Review 2026: Everything You Need to Know',
    description: 'A comprehensive review of the NeuroStar system — FDA clearances, clinical outcomes, patient experience, and how it compares to other TMS devices.',
    publishDate: '2026-05-04',
    category: 'research',
    author: 'Dr. Michael Torres',
    image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800&h=400&fit=crop',
    tags: ['neurostar', 'tms-device', 'fda-cleared', 'depression-treatment'],
    type: 'treatment_guide',
    condition: 'Major Depressive Disorder',
  },
  {
    slug: 'tms-for-veterans-ptsd-military',
    title: 'TMS for Veterans: How Brain Stimulation Is Helping Service Members with PTSD and Depression',
    description: 'Veterans face elevated rates of treatment-resistant depression and PTSD. TMS offers a non-invasive, medication-free option increasingly covered by VA benefits.',
    publishDate: '2026-05-11',
    category: 'treatment',
    author: 'Dr. Sarah Chen',
    image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=800&h=400&fit=crop',
    tags: ['veterans', 'ptsd', 'military', 'tms', 'va-coverage'],
    type: 'treatment_guide',
    condition: 'PTSD and Depression',
  },
  {
    slug: 'brainsway-deep-tms-comprehensive-guide',
    title: 'BrainsWay Deep TMS: The Complete 2026 Guide to H-Coil Technology',
    description: 'BrainsWay uses proprietary H-coils to deliver deep transcranial magnetic stimulation. Learn how it works, what conditions it treats, and what the outcomes look like.',
    publishDate: '2026-05-18',
    category: 'research',
    author: 'Dr. James Park',
    image: 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=800&h=400&fit=crop',
    tags: ['brainsway', 'deep-tms', 'h-coil', 'ocd', 'mdd'],
    type: 'treatment_guide',
    condition: 'Major Depressive Disorder',
  },
  {
    slug: 'tms-vs-ect-comparison-guide',
    title: 'TMS vs ECT: Which Brain Stimulation Treatment Is Right for You?',
    description: 'Both TMS and ECT treat severe depression — but they work very differently. A side-by-side comparison of efficacy, side effects, cost, and patient experience.',
    publishDate: '2026-05-25',
    category: 'treatment',
    author: 'Dr. Michael Torres',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=400&fit=crop',
    tags: ['tms', 'ect', 'brain-stimulation', 'depression', 'comparison'],
    type: 'treatment_guide',
    condition: 'Treatment-Resistant Depression',
  },

  // ── JUNE 2026 ──────────────────────────────────────────────────────────────
  {
    slug: 'magventure-tms-device-overview',
    title: 'MagVenture TMS: A Clinician\'s Overview of the MagPro System',
    description: 'MagVenture\'s MagPro and MagOption systems are widely used in academic medical centers. Here\'s how they work, their key protocols, and real-world outcomes data.',
    publishDate: '2026-06-01',
    category: 'research',
    author: 'Dr. James Park',
    image: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&h=400&fit=crop',
    tags: ['magventure', 'magpro', 'tms-device', 'rTMS'],
    type: 'treatment_guide',
    condition: 'Major Depressive Disorder',
  },
  {
    slug: 'tms-for-panic-disorder-anxiety',
    title: 'TMS for Panic Disorder: Can Magnetic Stimulation Stop Panic Attacks?',
    description: 'Panic disorder affects 2–3% of U.S. adults. Emerging research shows TMS targeting the prefrontal cortex can reduce panic frequency and severity.',
    publishDate: '2026-06-08',
    category: 'treatment',
    author: 'Dr. Sarah Chen',
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=400&fit=crop',
    tags: ['panic-disorder', 'anxiety', 'tms', 'brain-stimulation'],
    type: 'treatment_guide',
    condition: 'Panic Disorder',
  },
  {
    slug: 'tms-cost-insurance-guide-2026',
    title: 'Does Insurance Cover TMS in 2026? A State-by-State Breakdown',
    description: 'Insurance coverage for TMS varies dramatically by payer and state. This guide covers major insurers, prior auth requirements, and how to appeal a denial.',
    publishDate: '2026-06-15',
    category: 'insurance',
    author: 'Dr. Michael Torres',
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=400&fit=crop',
    tags: ['insurance', 'coverage', 'prior-authorization', 'cost'],
    type: 'insurance_guide',
    insurance: 'Major Insurance Plans',
  },
  {
    slug: 'theta-burst-stimulation-ibs-tms',
    title: 'Theta Burst Stimulation (iTBS): The Faster TMS Protocol Getting FDA Attention',
    description: 'Intermittent theta burst stimulation delivers the same results as standard TMS in just 3 minutes per session. Here\'s what the 2026 research says about iTBS efficacy.',
    publishDate: '2026-06-22',
    category: 'research',
    author: 'Dr. James Park',
    image: 'https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=800&h=400&fit=crop',
    tags: ['theta-burst', 'itbs', 'accelerated-tms', 'protocol'],
    type: 'research_summary',
    topic: 'Theta Burst Stimulation efficacy and FDA clearance',
  },
  {
    slug: 'tms-for-suicidal-ideation',
    title: 'TMS for Suicidal Ideation: What the 2026 Evidence Shows',
    description: 'Reducing suicidal thoughts is the most urgent goal in depression treatment. New studies explore whether TMS can provide rapid reduction in suicidality.',
    publishDate: '2026-06-29',
    category: 'treatment',
    author: 'Dr. Sarah Chen',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop',
    tags: ['suicidal-ideation', 'crisis', 'tms', 'depression', 'safety'],
    type: 'treatment_guide',
    condition: 'Depression with Suicidal Ideation',
  },

  // ── JULY 2026 ──────────────────────────────────────────────────────────────
  {
    slug: 'tms-for-fibromyalgia-chronic-pain',
    title: 'TMS for Fibromyalgia and Chronic Pain: New Evidence for 2026',
    description: 'TMS isn\'t just for depression. Research increasingly supports using it for fibromyalgia pain, migraine, and other chronic pain conditions affecting millions.',
    publishDate: '2026-07-06',
    category: 'treatment',
    author: 'Dr. Michael Torres',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=400&fit=crop',
    tags: ['fibromyalgia', 'chronic-pain', 'migraine', 'tms'],
    type: 'treatment_guide',
    condition: 'Fibromyalgia and Chronic Pain',
  },
  {
    slug: 'saint-protocol-stanford-tms',
    title: 'SAINT Protocol: Stanford\'s Accelerated TMS — From 6 Weeks to 5 Days',
    description: 'The SAINT protocol achieved 90% remission rates in Stanford trials by compressing TMS into an accelerated, closed-loop schedule. What it means for patients in 2026.',
    publishDate: '2026-07-13',
    category: 'research',
    author: 'Dr. James Park',
    image: 'https://images.unsplash.com/photo-1620722627240-681e5517e8ff?w=800&h=400&fit=crop',
    tags: ['saint', 'stanford', 'accelerated-tms', 'protocol', 'remission'],
    type: 'research_summary',
    topic: 'SAINT Protocol outcomes and accelerated TMS',
  },
  {
    slug: 'aetna-tms-coverage-guide',
    title: 'Aetna TMS Coverage 2026: Prior Authorization, Eligibility, and Appeals',
    description: 'Aetna covers TMS for treatment-resistant depression but requires step therapy and prior authorization. Here\'s how to navigate their requirements and get approved.',
    publishDate: '2026-07-20',
    category: 'insurance',
    author: 'Dr. Michael Torres',
    image: 'https://images.unsplash.com/photo-1559526324-593bc073d938?w=800&h=400&fit=crop',
    tags: ['aetna', 'insurance', 'prior-auth', 'coverage'],
    type: 'insurance_guide',
    insurance: 'Aetna',
  },
  {
    slug: 'tms-for-tinnitus-hearing-loss',
    title: 'Can TMS Silence Tinnitus? Exploring Magnetic Stimulation for Ringing in the Ears',
    description: 'Tinnitus affects 15% of Americans with no reliable cure. TMS targeting the auditory cortex is showing promise as a treatment that addresses the root neurological cause.',
    publishDate: '2026-07-27',
    category: 'treatment',
    author: 'Dr. Sarah Chen',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop',
    tags: ['tinnitus', 'hearing', 'neuro-modulation', 'tms'],
    type: 'treatment_guide',
    condition: 'Tinnitus',
  },

  // ── AUGUST 2026 ─────────────────────────────────────────────────────────────
  {
    slug: 'tms-for-ocd-deep-brain-stimulation',
    title: 'TMS for OCD: Deep TMS vs Standard rTMS — Which Approach Works Better?',
    description: 'OCD affects 1–2% of the global population. With FDA clearance for deep TMS and active trials for standard rTMS, here\'s how to choose the right protocol.',
    publishDate: '2026-08-03',
    category: 'treatment',
    author: 'Dr. James Park',
    image: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800&h=400&fit=crop',
    tags: ['ocd', 'deep-tms', 'brainsway', 'compulsive', 'brain-stimulation'],
    type: 'treatment_guide',
    condition: 'Obsessive-Compulsive Disorder',
  },
  {
    slug: 'cigna-tms-coverage-guide',
    title: 'Cigna TMS Coverage 2026: Requirements, Network Providers, and Cost Estimates',
    description: 'Cigna covers TMS therapy under specific clinical criteria. Learn exactly what Cigna requires for approval, which CPT codes they recognize, and how to estimate your out-of-pocket cost.',
    publishDate: '2026-08-10',
    category: 'insurance',
    author: 'Dr. Michael Torres',
    image: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&h=400&fit=crop',
    tags: ['cigna', 'insurance', 'coverage', 'cpt-codes'],
    type: 'insurance_guide',
    insurance: 'Cigna',
  },
  {
    slug: 'tms-for-stroke-recovery',
    title: 'TMS for Post-Stroke Recovery: Can Magnetic Stimulation Rebuild Motor Function?',
    description: 'After a stroke, rehabilitation is critical — but recovery plateaus for most patients. TMS combined with physical therapy is showing new promise for restoring motor and language function.',
    publishDate: '2026-08-17',
    category: 'treatment',
    author: 'Dr. Sarah Chen',
    image: 'https://images.unsplash.com/photo-1583912268183-eb7f4d6b3e16?w=800&h=400&fit=crop',
    tags: ['stroke', 'rehabilitation', 'motor-function', 'neuro-recovery'],
    type: 'treatment_guide',
    condition: 'Post-Stroke Recovery',
  },
  {
    slug: 'tms-for-executives-burnout',
    title: 'TMS for High-Functioning Professionals: Burnout, Depression, and the Executive Brain',
    description: 'Senior executives and high-performers face unique mental health challenges. TMS offers a discreet, non-pharmaceutical option that fits into demanding schedules.',
    publishDate: '2026-08-24',
    category: 'patient-guide',
    author: 'Dr. Michael Torres',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=400&fit=crop',
    tags: ['executives', 'burnout', 'professionals', 'high-functioning'],
    type: 'treatment_guide',
    condition: 'Burnout and Depression in Professionals',
  },
  {
    slug: 'united-healthcare-tms-coverage',
    title: 'UnitedHealthcare TMS Coverage 2026: Everything You Need to Know',
    description: 'UnitedHealthcare is one of the largest payers in the U.S. This guide covers their TMS medical policy, step therapy requirements, and strategies for getting your claim approved.',
    publishDate: '2026-08-31',
    category: 'insurance',
    author: 'Dr. James Park',
    image: 'https://images.unsplash.com/photo-1434626881859-194d67b2b86f?w=800&h=400&fit=crop',
    tags: ['united-healthcare', 'uhc', 'insurance', 'coverage'],
    type: 'insurance_guide',
    insurance: 'UnitedHealthcare',
  },

  // ── SEPTEMBER 2026 ──────────────────────────────────────────────────────────
  {
    slug: 'tms-for-migraine-prevention',
    title: 'TMS for Migraine Prevention: FDA-Cleared Devices and Clinical Evidence',
    description: 'Migraine is the #1 cause of disability under 50. Single-pulse TMS (sTMS) devices are FDA-cleared for acute migraine with aura. Here\'s what the research says for 2026.',
    publishDate: '2026-09-07',
    category: 'treatment',
    author: 'Dr. Sarah Chen',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=400&fit=crop',
    tags: ['migraine', 'headache', 'spms', 'fda-cleared', 'pain'],
    type: 'treatment_guide',
    condition: 'Migraine',
  },
  {
    slug: 'tms-for-autism-spectrum-asd',
    title: 'TMS for Autism Spectrum Disorder: What the Science Actually Says in 2026',
    description: 'Parents and clinicians are increasingly interested in TMS for ASD. This article examines the evidence — what\'s been shown to work, what\'s still experimental, and what the risks are.',
    publishDate: '2026-09-14',
    category: 'research',
    author: 'Dr. James Park',
    image: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&h=400&fit=crop',
    tags: ['autism', 'asd', 'neurodevelopment', 'tms-research'],
    type: 'research_summary',
    topic: 'TMS for Autism Spectrum Disorder outcomes and safety',
  },
  {
    slug: 'tms-for-pregnancy-postpartum',
    title: 'TMS During Pregnancy and Postpartum: A Safe Option When Antidepressants Aren\'t an Answer',
    description: 'Many pregnant and breastfeeding women need depression treatment but want to avoid medications. TMS targets the brain directly without systemic drug exposure — here\'s what the safety data shows.',
    publishDate: '2026-09-21',
    category: 'treatment',
    author: 'Dr. Sarah Chen',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=400&fit=crop',
    tags: ['pregnancy', 'postpartum', 'perinatal', 'breastfeeding', 'antidepressants'],
    type: 'treatment_guide',
    condition: 'Perinatal and Postpartum Depression',
  },
  {
    slug: 'tms-for-insomnia-sleep',
    title: 'TMS for Insomnia: Targeting the Overactive Prefrontal Cortex',
    description: 'Sleep disorders and depression are deeply interconnected. TMS applied to the dorsolateral prefrontal cortex can normalize sleep architecture and improve both sleep quality and mood.',
    publishDate: '2026-09-28',
    category: 'treatment',
    author: 'Dr. Michael Torres',
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&h=400&fit=crop',
    tags: ['insomnia', 'sleep', 'depression', 'dlpfc'],
    type: 'treatment_guide',
    condition: 'Insomnia and Sleep Disorders',
  },

  // ── OCTOBER 2026 ───────────────────────────────────────────────────────────
  {
    slug: 'tms-for-bipolar-depression-guide',
    title: 'TMS for Bipolar Depression: Safety, Efficacy, and Why It\'s Different from Unipolar Treatment',
    description: 'Using TMS in bipolar disorder requires careful monitoring for mania induction. This guide covers the latest protocols optimized for bipolar patients, including accelerated and bilateral approaches.',
    publishDate: '2026-10-05',
    category: 'treatment',
    author: 'Dr. James Park',
    image: 'https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&h=400&fit=crop',
    tags: ['bipolar', 'mania', 'mood-stabilizers', 'bipolar-depression'],
    type: 'treatment_guide',
    condition: 'Bipolar Depression',
  },
  {
    slug: 'tms-for-adhd-north-america',
    title: 'TMS for ADHD in Adults: Can Magnetic Stimulation Improve Focus and Impulsivity?',
    description: 'ADHD affects 4–5% of adults and is frequently treatment-resistant to medication. TMS targeting the DLPFC and default mode network is emerging as a non-stimulant option.',
    publishDate: '2026-10-12',
    category: 'treatment',
    author: 'Dr. Sarah Chen',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=400&fit=crop',
    tags: ['adhd', 'focus', 'attention', 'adults', 'executive-function'],
    type: 'treatment_guide',
    condition: 'Adult ADHD',
  },
  {
    slug: 'medicare-tms-coverage-2026',
    title: 'Medicare TMS Coverage in 2026: LCD Updates, Reimbursement Rates, and How to Bill',
    description: 'Medicare covers TMS under Part B when provided in an office setting. This article walks through the current Local Coverage Determination requirements, eligible diagnoses, and billing codes.',
    publishDate: '2026-10-19',
    category: 'insurance',
    author: 'Dr. Michael Torres',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=400&fit=crop',
    tags: ['medicare', 'cms', 'part-b', 'lcd', 'billing', 'reimbursement'],
    type: 'insurance_guide',
    insurance: 'Medicare',
  },
  {
    slug: 'tms-for-eating-disorders-anorexia-bulimia',
    title: 'TMS for Eating Disorders: Emerging Research on Anorexia, Bulimia, and Binge Eating',
    description: 'Eating disorders have some of the highest mortality rates of any psychiatric condition. TMS is being studied as a tool to reduce craving, compulsivity, and rumination in anorexia, bulimia, and BED.',
    publishDate: '2026-10-26',
    category: 'treatment',
    author: 'Dr. James Park',
    image: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=800&h=400&fit=crop',
    tags: ['eating-disorders', 'anorexia', 'bulimia', 'binge-eating', 'body-image'],
    type: 'treatment_guide',
    condition: 'Eating Disorders',
  },

  // ── NOVEMBER 2026 ──────────────────────────────────────────────────────────
  {
    slug: 'tms-for-schizophrenia-negative-symptoms',
    title: 'TMS for Schizophrenia: Targeting Negative Symptoms and Cognitive Impairment',
    description: 'Antipsychotics treat psychosis but often leave negative symptoms and cognitive deficits untreated. TMS applied to the prefrontal cortex shows promise for these underserved aspects of schizophrenia.',
    publishDate: '2026-11-02',
    category: 'research',
    author: 'Dr. Sarah Chen',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=400&fit=crop',
    tags: ['schizophrenia', 'psychosis', 'negative-symptoms', 'cognitive'],
    type: 'research_summary',
    topic: 'TMS for negative symptoms and cognitive impairment in schizophrenia',
  },
  {
    slug: 'tms-for-parkinsons-disease',
    title: 'TMS for Parkinson\'s Disease: Motor Symptoms, Depression, and Quality of Life',
    description: 'Parkinson\'s affects over 1 million Americans. TMS is being studied for motor symptoms, freezing of gait, and the depression that affects up to 40% of Parkinson\'s patients.',
    publishDate: '2026-11-09',
    category: 'treatment',
    author: 'Dr. Michael Torres',
    image: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=800&h=400&fit=crop',
    tags: ['parkinsons', 'motor-symptoms', 'tremor', 'neurodegenerative'],
    type: 'treatment_guide',
    condition: 'Parkinson\'s Disease',
  },
  {
    slug: 'tms-combined-with-therapy-cbt',
    title: 'Combining TMS with Therapy: Why TMS + CBT or ERP Produces Better Outcomes',
    description: 'TMS and psychotherapy work through different mechanisms — brain stimulation vs. cognitive restructuring. Emerging evidence suggests combining them yields higher and more durable remission rates.',
    publishDate: '2026-11-16',
    category: 'research',
    author: 'Dr. James Park',
    image: 'https://images.unsplash.com/photo-1573497019418-b400bb3ab074?w=800&h=400&fit=crop',
    tags: ['tms', 'cbt', 'erp', 'combined-therapy', 'psychotherapy'],
    type: 'research_summary',
    topic: 'Combined TMS and psychotherapy outcomes',
  },
  {
    slug: 'tms-for-alzheimers-dementia',
    title: 'TMS for Alzheimer\'s and Dementia: What the 2026 Research Shows About Cognitive Stimulation',
    description: 'As the population ages, Alzheimer\'s prevalence is rising sharply. TMS applied to the prefrontal cortex and memory networks is being investigated as a way to slow cognitive decline.',
    publishDate: '2026-11-23',
    category: 'research',
    author: 'Dr. Sarah Chen',
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=800&h=400&fit=crop',
    tags: ['alzheimers', 'dementia', 'cognitive-decline', 'memory', 'aging'],
    type: 'research_summary',
    topic: 'TMS for Alzheimer\'s disease and cognitive decline',
  },

  // ── DECEMBER 2026 ──────────────────────────────────────────────────────────
  {
    slug: 'tms-year-in-review-2026',
    title: 'TMS Therapy Year in Review 2026: Key Approvals, Studies, and What\'s Next',
    description: 'From SAINT protocol expansions to new FDA indications, 2026 was a pivotal year for TMS. This comprehensive review covers the biggest developments and what patients can expect in 2027.',
    publishDate: '2026-12-01',
    category: 'research',
    author: 'Dr. Michael Torres',
    image: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&h=400&fit=crop',
    tags: ['2026', 'year-in-review', 'fda', 'research', 'trends'],
    type: 'research_summary',
    topic: '2026 TMS therapy developments and FDA approvals',
  },
  {
    slug: 'tms-for-multiple-sclerosis-fatigue',
    title: 'TMS for Multiple Sclerosis: Addressing Fatigue, Depression, and Cognitive Fog',
    description: 'Multiple sclerosis patients commonly experience severe fatigue and depression that don\'t respond well to MS medications alone. TMS targeting the motor cortex and DLPFC is showing meaningful benefits.',
    publishDate: '2026-12-07',
    category: 'treatment',
    author: 'Dr. James Park',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&h=400&fit=crop',
    tags: ['multiple-sclerosis', 'ms', 'fatigue', 'demyelination'],
    type: 'treatment_guide',
    condition: 'Multiple Sclerosis',
  },
  {
    slug: 'tms-for-adolescents-pediatric-guide',
    title: 'TMS for Children and Adolescents: Safety, Ethics, and the Evidence Behind Pediatric TMS',
    description: 'TMS is increasingly used off-label for children and adolescents with depression. This guide covers FDA status, safety data in pediatric populations, and what parents need to know.',
    publishDate: '2026-12-14',
    category: 'patient-guide',
    author: 'Dr. Sarah Chen',
    image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=400&fit=crop',
    tags: ['adolescents', 'pediatric', 'children', 'parents', 'safety'],
    type: 'treatment_guide',
    condition: 'Adolescent Depression',
  },
  {
    slug: 'tms-for-alcohol-dependence-addiction',
    title: 'TMS for Alcohol Use Disorder: Can Magnetic Stimulation Reduce Cravings?',
    description: 'Alcohol dependence affects 29.5 million Americans. TMS targeting the dorsolateral prefrontal cortex can reduce craving intensity and support abstinence — here\'s what the 2026 evidence shows.',
    publishDate: '2026-12-21',
    category: 'treatment',
    author: 'Dr. Michael Torres',
    image: 'https://images.unsplash.com/photo-1527689368864-3a821dbccc34?w=800&h=400&fit=crop',
    tags: ['alcohol', 'addiction', 'substance-use', 'craving', 'cue-reactivity'],
    type: 'treatment_guide',
    condition: 'Alcohol Use Disorder',
  },
  {
    slug: 'tms-2027-outlook-predictions',
    title: 'TMS Therapy in 2027: What\'s Coming — AI Navigation, New Devices, and Expanded Indications',
    description: 'The TMS field is advancing faster than ever. From AI-guided neuronavigation to new FDA indications on the horizon, here\'s what the next 12 months hold for brain stimulation therapy.',
    publishDate: '2026-12-28',
    category: 'research',
    author: 'Dr. James Park',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=400&fit=crop',
    tags: ['2027', 'outlook', 'ai', 'neuronavigation', 'future', 'predictions'],
    type: 'research_summary',
    topic: 'TMS therapy outlook, new devices, and AI navigation for 2027',
  },
] as const;

export type ScheduledPost = (typeof SCHEDULED_POSTS)[number];
